name: Explorer Neko

on:
  workflow_dispatch:

jobs:
  explore:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4
      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Installer requests
        run: pip install requests
      - name: Explorer
        run: python explore_neko.py
